name: Package

on:
  release:
    types: [published]

jobs:
  release_artifacts:
    name: Release Artifacts (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Meson
        uses: ./.github/actions/meson-setup
        with:
          meson-setup-args: >-
            -Ddefault_library=static

      - name: Compile all files
        run: meson compile -C build

      - uses: actions/upload-artifact@v4
        with:
          name: dasn1-amd64-linux
          path: ./build/tools/dasn1/dasn1
          if-no-files-found: error