name: Package

on:
  release:
    types: [published]

jobs:
  create_dists:
    name: Create Dist Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/meson-setup

      # This is largely to render the template files
      - name: Build
        run: meson compile -C build

      - name: Create Source Dist
        run: meson dist -C build --no-tests --formats gztar

      - name: Rename Source Dist
        run: mv build/meson-dist/*.tar.gz juptune-source.tar.gz

      - name: Create DevOps Dist
        run: tar -czvf devops.tar.gz build/devops/pkg

      - uses: actions/upload-artifact@v2
        with:
          name: dists
          path: |
            juptune-source.tar.gz
            devops.tar.gz

  # I can't sign up for the OpenSUSE Build Service because the login page is broken.
  # Dodgy unsigned RPMs it is.
  opensuse_rpm:
    name: Create OpenSUSE RPM
    runs-on: opensuse/tumbleweed
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v2
        with:
          name: dists
          path: dists

      - name: Unzip DevOps Dist
        run: tar -xzvf dists/devops.tar.gz

      - name: Install Build Dependencies
        run: >-
            zypper -n in --no-recommends --auto-agree-with-licenses 
              meson 
              ldc-phobos-devel 
              pkg-config
              rpm-build
      
      - name: Setup RPM Build Environment
        run: mkdir ~/rpmbuild/SOURCES

      - name: Copy Source Dist
        run: cp dists/juptune-source.tar.gz ~/rpmbuild/SOURCES

      - name: Perform build
        run: rpmbuild -ba build/devops/pkg/opensuse-rpm/juptune.spec

      - name: Rename RPMs
        run: |
            for file in $(ls ~/rpmbuild/RPMS/x86_64/); do
              mv -v ~/rpmbuild/RPMS/x86_64/${file} ~/rpmbuild/RPMS/x86_64/opensuse-${file}
            done
            for file in $(ls ~/rpmbuild/SRPMS/); do
              mv -v ~/rpmbuild/SRPMS/${file} ~/rpmbuild/SRPMS/opensuse-${file}
            done

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ~/rpmbuild/RPMS/x86_64/*.rpm
            ~/rpmbuild/SRPMS/*.src.rpm