name: Package

on:
  release:
    types: [published]

jobs:
  create_dists:
    name: Create Dist Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/meson-setup

      - name: Check that tag matches Meson project version
        run: |
          meson_version=$(meson introspect build --projectinfo | jq -r .version)
          if [ "${meson_version}" != "${{ github.ref }}" ]; then
            echo "=========================================="
            echo " Tag does not match Meson project version "
            echo " Please edit meson.build to match the tag "
            echo "=========================================="
            echo "  meson_version: ${meson_version}         "
            echo "  github.ref:    ${{ github.ref }}        "
            exit 1
          fi
      
      - uses: ./.github/actions/meson-dist

  # I can't sign up for the OpenSUSE Build Service because the login page is broken.
  # Dodgy unsigned RPMs it is.
  opensuse_rpm:
    name: Create OpenSUSE RPM
    needs: create_dists
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed:latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v2
        with:
          name: dists
          path: dists

      - name: Unzip DevOps Dist
        run: tar -xzvf dists/devops.tar.gz