name: Package

on:
  release:
    types: [published]

jobs:
  create_dists:
    name: Create Dist Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/meson-setup

      - name: Check that tag matches Meson project version
        run: |
          meson_version=$(meson introspect build --projectinfo | jq -r .version)
          if [ "${meson_version}" != "${{ github.ref }}" ]; then
            echo "=========================================="
            echo " Tag does not match Meson project version "
            echo " Please edit meson.build to match the tag "
            echo "=========================================="
            echo "  meson_version: ${meson_version}         "
            echo "  github.ref:    ${{ github.ref }}        "
            exit 1
          fi
      
      - uses: ./.github/actions/meson-dist

  # The sparse docs around OBS are testing my patience, so I'm just going to
  # do the releases manually and hope I don't forget (what a shame that would be).s
  # opensuse_rpm: