name: Unittests

on:
  pull_request: 
  push:

jobs:
  linux_test:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Meson
        uses: ./.github/actions/meson-setup
        with:
          meson-setup-args: >-
            -Ddefault_library=static

      - name: Build
        run: meson compile -C build

      - name: Test
        run: meson test -C build

      - name: Test Install can be used, and generates a working executable
        run: |
          meson install -C build
          cat ./build/meson-private/juptune.pc
          mkdir tmp
          mv ./build/meson-private/juptune.pc tmp/
          export PKG_CONFIG_PATH=$(pwd)/tmp
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)/install/lib/x86_64-linux-gnu

          cd examples/basic-meson-project
          meson setup build
          meson compile -C build
          ./build/basic-meson-project