name: Test

on:
  pull_request: 
  push:

jobs:
  linux_test:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Tooling (apt)
        run: sudo apt update && sudo apt install -y python3-pip yasm

      - name: Install Tooling (pip)
        run: pip3 install meson ninja

      - name: Install Dlang
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest

      - name: Configure Meson
        run: meson setup build --prefix ./install

      - name: Build
        run: meson compile -C build

      - name: Test
        run: meson test -C build

      - name: Test Install can be used, and generates a working executable
        run: |
          meson install -C build
          cat ./build/meson-uninstalled/juptune-uninstalled.pc
          export PKG_CONFIG_PATH=$(pwd)/build/meson-uninstalled

          cd examples/basic-meson-project
          meson setup build
          meson compile -C build
          ./build/basic-meson-project